---
- name: Setup FirewallD
  hosts: localhost
  tasks: 
    - name: Install FirewallD
      dnf:
        name: 
          - firewalld
        state: present
    
    - name: Enable and start FirewallD service
      systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Allow HTTP traffic
      ansible.posix.firewalld:
        zone: public
        service: http
        permanent: yes
        immediate: true
        state: enabled
    
    - name: Allow HTTPS traffic
      ansible.posix.firewalld:
        zone: public
        service: https
        permanent: yes
        immediate: true
        state: enabled

    - name: Allow Firefly traffic
      ansible.posix.firewalld:
        zone: public
        port: 8080/tcp
        permanent: yes
        immediate: true
        state: enabled
