---
- name: Setup Firefly
  hosts: localhost
  vars_prompt:
    - name: cron_token
      prompt: "Enter cron_token"
      private: no
    - name: db_password
      prompt: "Enter db_password"
      private: no
    - name: app_key
      prompt: "Enter app_key"
      private: no
  tasks:
    - name: Install Docker
      ansible.builtin.dnf: 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Install Remi RPM repository
      ansible.builtin.dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
        state: present
        disable_gpg_check: true

    - name: Reset PHP module
      command: dnf module reset php

    - name: Enable PHP 8.3 
      command: dnf module enable php:remi-8.3 -y

    - name: Install PHP
      ansible.builtin.dnf:
        name: php
        state: present

    - name: Ensure ~/firefly exists
      file:
        path: ~/firefly
        state: directory

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Copy docker-compose.yml
      template: 
        src: ~/repos/hetzner-setup/templates/firefly-docker-compose.yml
        dest: ~/firefly/docker-compose.yml
    
    - name: Copy .env
      template: 
        src: ~/repos/hetzner-setup/templates/firefly.env
        dest: ~/firefly/.env
    
    - name: Copy db.env
      template: 
        src: ~/repos/hetzner-setup/templates/firefly.db.env
        dest: ~/firefly/.db.env

    - name: Run Docker Compose
      command: docker compose -f ~/firefly/docker-compose.yml up -d --pull always