---
- name: Setup MariaDB
  hosts: localhost
  tasks: 
  - name: Download MariaDB repository setup script
    ansible.builtin.get_url:
      url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
      dest: /tmp/mariadb_repo_setup
  
  - name: Run MariaDB repository setup script
    ansible.builtin.command: bash /tmp/mariadb_repo_setup
  
  - name: Install MariaDB
    ansible.builtin.dnf:
      name:
        - mariadb-server
        - mariadb-backup
      state: present
  
  - name: Start and enable MariaDB service
    ansible.builtin.systemd:
      name: mariadb
      state: started
      enabled: yes